import 'dart:convert';
import 'dart:io' show gzip;
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show compute;
import 'package:flutter/services.dart' show rootBundle;

/// Bundled scripture texts: every volume ships inside the app as
/// `assets/books/{id}.json.gz` (1809 files, ~56MB), so reading never needs
/// the network. Generated by `scripts/generate-book-assets.js`.
class BookAssets {
  BookAssets._();

  /// Loads and decodes one bundled volume, or null if the asset is missing
  /// (caller falls back to the network/outbox path).
  /// Gunzip + JSON parsing run in a background isolate to keep UI smooth —
  /// the largest volume is ~8MB of JSON.
  static Future<({String metaJson, String juansJson})?> tryLoad(
    String bookId,
  ) async {
    final ByteData data;
    try {
      data = await rootBundle.load('assets/books/$bookId.json.gz');
    } catch (_) {
      return null;
    }
    final bytes = data.buffer.asUint8List(
      data.offsetInBytes,
      data.lengthInBytes,
    );
    return compute(_decode, bytes);
  }

  static ({String metaJson, String juansJson}) _decode(Uint8List gzBytes) {
    final json =
        jsonDecode(utf8.decode(gzip.decode(gzBytes))) as Map<String, dynamic>;
    return (
      metaJson: jsonEncode(json['meta'] ?? const <String, dynamic>{}),
      juansJson: jsonEncode(json['juans'] ?? const <dynamic>[]),
    );
  }
}
